name: Docker Build & Publish

on:
  push:
    branches: [main]

jobs:
  build-push:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4
    
      - name: Configure Vars
        id: conf
        shell: bash
        run: |
            echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
            echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    #   - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🚢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/codesark-portfolio:${{ steps.conf.outputs.branch }}-${{ steps.conf.outputs.sha_short }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/codesark-portfolio:${{ steps.conf.outputs.branch }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/codesark-portfolio:latest
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
    outputs:
      branch: ${{ steps.conf.outputs.branch }}
      sha_short: ${{ steps.conf.outputs.sha_short }}
